language: python

before_install:
 - pip install codecov

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django17
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=py35-django110
  - TOX_ENV=py36-django17
  - TOX_ENV=py36-django18
  - TOX_ENV=py36-django19
  - TOX_ENV=py36-django110
  - TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

sudo: false
